package MyArkanoid;

import utils.FileUtils;

import javax.swing.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class playGame extends JFrame {



    public playGame() {
        try {
            initComponents();
            arkanoidGame1.loadLevel(FileUtils.createFile("puzzle.txt"));


    } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(playGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arkanoidGame1 = new ArkanoidGame();
        btSave = new JButton();
        btLoad = new JButton();
        btPause = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btLoad.setText("Load");
        btLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadActionPerformed(evt);
            }
        });

        btPause.setText("Pause");
        btPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPauseActionPerformed(evt);
            }
        });


        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(btSave)
                    .addComponent(btLoad))
                    .addComponent(btPause)
                .addGap(18, 18, 18)
                .addComponent(arkanoidGame1, GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))

        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btSave)
                .addGap(29, 29, 29)
                .addComponent(btLoad)
                    .addGap(29, 29, 29)
                    .addComponent(btPause)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(arkanoidGame1, GroupLayout.PREFERRED_SIZE, 432, GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPauseActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (arkanoidGame1.timer.isRunning()){
                arkanoidGame1.timer.stop();
                return;
            }
            arkanoidGame1.timer.start();
        }
        catch (Exception ex) {
            Logger.getLogger(playGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }



    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        arkanoidGame1.stopGame();

        JFileChooser fc = new JFileChooser(".");
        int result = fc.showSaveDialog(this);
        if( result == JFileChooser.APPROVE_OPTION){
            try {
                arkanoidGame1.saveGame(fc.getSelectedFile().getAbsolutePath());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(playGame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        arkanoidGame1.continueGame();
    }//GEN-LAST:event_btSaveActionPerformed

    private void btLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadActionPerformed
        arkanoidGame1.stopGame();
        JFileChooser fc = new JFileChooser(".");
        int result = fc.showOpenDialog(this);
        if( result == JFileChooser.APPROVE_OPTION){
            try {
                arkanoidGame1.loadGame(fc.getSelectedFile().getAbsolutePath());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                Logger.getLogger(playGame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        arkanoidGame1.continueGame();
    }//GEN-LAST:event_btLoadActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ArkanoidGame arkanoidGame1;
    private JButton btLoad;
    private JButton btSave;
    private JButton btPause;
    // End of variables declaration//GEN-END:variables
}
